EmployeeRecordMgmt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from . import views  # Import views from main app

# from django.contrib.auth.models import Group

admin.site.site_header = "Jobseeker Records"
# admin.site.unregister(Group)



urlpatterns = [
    path('admin/', admin.site.urls),
    path('employee/',include("employee.urls")),
    path('job/',include("job.urls")),
    path('users/',include("users.urls")),
    path('notification/',include("notification.urls")),
    path('', views.home, name='home'),  # Add this line for the hero page



    # path('images/covers')                        

] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

job/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings
from .api import api_search


app_name = "job"

urlpatterns = [
    path("api/search",api_search,name = "api_search"),
    path("search/",views.search,name = "search"),
    path("<int:job_id>/edit", views.edit, name="edit"),
    path("<int:application_id>/edit_app", views.edit_app, name="edit_app"),
    path("search_jobs", views.search_jobs, name="search_jobs"),

    path("<int:job_id>", views.job_detail, name="job_detail"),
    path("job/add" ,views.add, name="add"),
    path("<int:job_id>/apply_for_job/" ,views.apply_for_job, name="apply_for_job "),
    path("delete_application/<int:application_id>",views.delete_application,name="delete_application"),
    path("job_pdf",views.job_pdf,name="job_pdf"),
    path('job-application/<int:application_id>/approve/', views.approve_job_application, name='approve_job_application'),
    path('job-application/<int:application_id>/decline/', views.decline_job_application, name='decline_job_application'),

    ]



urlpatterns += static (settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path("dashboard", views.dashboard, name="dashboard"),
    path("job/<int:job_id>/", views.view_dashboard_job, name="view_dashboard_job"),
    path("view_application/<int:application_id>/", views.view_application , name="view_application"),
    

    ]

job/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Count


GENDER = (('M', 'Male'), ('F', 'Female'), ('O', 'Other'))



class Job(models.Model):

    

    COMPUTER_SUPPORT_SPECIALIST = 'Computer Support Specialist'
    HARDWARE_ENGINEER = 'Hardware Engineer'
    COMPUTER_SYSTEM_ANALYST = 'Computer System Analyst'
    SOFTWARE_DEVELOPER = 'Software Developer'
    PROGRAMMER = 'Programmer'
    WEB_DEVELOPER = 'Web Developer'
    NETWORK_ENGINEER = 'Network Engineer'
    SOFTWARE_TESTER = 'Software Tester'
    FRONTEND_DEVELOPER = "Frontend Developer"
    BACKEND_DEVELOPER = "Backend Developer"

    CHOICES_SIZE =   ( (COMPUTER_SUPPORT_SPECIALIST ,'COMPUTER_SUPPORT_SPECIALIST'),
    ( HARDWARE_ENGINEER ,'HARDWARE_ENGINEER'),
    ( COMPUTER_SYSTEM_ANALYST, 'COMPUTER_SYSTEM_ANALYST' ),
    ( SOFTWARE_DEVELOPER, 'SOFTWARE_DEVELOPER'),
    ( PROGRAMMER , 'PROGRAMMER'),
    ( WEB_DEVELOPER,'WEB_DEVELOPER'),
    ( NETWORK_ENGINEER,'NETWORK_ENGINEER'),
    ( SOFTWARE_TESTER,'SOFTWARE_TESTER'),
    (FRONTEND_DEVELOPER,"FRONTEND_DEVELOPER"),
    (BACKEND_DEVELOPER,"BACKEND_DEVELOPER")
    )

      
    ACTIVE = 'active'
    EMPLOYED = 'employed'
    ARCHIVED = 'archived'

    
    CHOICES_STATUS = (
        (EMPLOYED,'Employed'),
        (ACTIVE,'Active' ),
        (ARCHIVED,'Archived' )
     )

    title = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    skillset_required = models.TextField(null=True)
    about_job= models.TextField(blank=True, null=True)
    image = models.ImageField(upload_to="covers/",null=True,blank=True)
    experience = models.CharField(max_length=100,null=True)
    salary = models.CharField(max_length=50,null=True)
    deadline = models.CharField(max_length=50,null=True)

    department_name = models.CharField( max_length=30,choices=CHOICES_SIZE)

    
    created_by = models.ForeignKey(User,
                                   related_name="jobs",
                                   on_delete=models.CASCADE)
    status = models.CharField(max_length=20,choices=CHOICES_STATUS,default='active')
    
    def __str__(self):
        return self.title
    
        
    class Meta:
        ordering = ['-created_at']

    
class Application(models.Model):

    APPROVED = 'approved'
    PENDING = 'pending'
    DECLINED = 'declined'

    CHOICES_STATUS = (
        (APPROVED,'Approved'),
        (PENDING,'Pending' ),
        (DECLINED,'Declined' )
    )
    
    HIGH_SCHOOL = 'High School'
    ASSOCIATE_DEGREE = 'Associate Degree'
    BACHELOR_DEGREE = 'Bachelor Degree'
    MASTER_DEGREE = 'Master Degree'
    DOCTORATE = 'Doctorate'
    PROFESSIONAL_DEGREE = 'Professional Degree'
    CERTIFICATE = 'Certificate'
    DIPLOMA = 'Diploma'
    


    EDUCATION_CHOICES = ((HIGH_SCHOOL, 'High School'),
        (ASSOCIATE_DEGREE, 'Associate Degree'),
        (BACHELOR_DEGREE, "Bachelor's Degree"),
        (MASTER_DEGREE, "Master's Degree"),
        (DOCTORATE, 'Doctoral Degree'),
        (PROFESSIONAL_DEGREE, 'Professional Degree'),
        (CERTIFICATE, 'Certificate'),
        (DIPLOMA, 'Diploma')
    )

    job = models.ForeignKey(Job,
                            related_name='applications',
                             on_delete=models.CASCADE)
    first_name = models.CharField(max_length=200, null=True, blank=True)
    last_name = models.CharField(max_length=200, null=True, blank=True)
    date_of_birth = models.CharField(max_length=20, blank=True, null=True)
    gender = models.CharField(max_length=1,
                              choices=GENDER,
                              blank=False,
                              null=True)
    email = models.EmailField(max_length=70, blank=True, unique=True)
    location = models.CharField(
        max_length=104,
        null=True
    )
    mobile = models.IntegerField(null=True, blank=True)
    education   = models.CharField( max_length=2553, null=True, blank=True)

    level_education = models.CharField(max_length=30, choices=EDUCATION_CHOICES)


    content = models.TextField()
    experience = models.TextField()
    
    resume  = models.FileField( upload_to="resumes/", null=True, blank=True)
    
    created_at = models.DateTimeField(auto_now_add=True,null=False)
    status = models.CharField(max_length=20,choices=CHOICES_STATUS,default='pending')

    created_by = models.ForeignKey(User,
                                   related_name="applications",
                                   on_delete=models.CASCADE)

    class Meta:
        ordering = ['-created_at']


    

class ApplicationSummary(Application):
        class Meta:
          proxy = True
        verbose_name = 'Application Summary'

        def job_title(self):
            return self.job.title

users/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
from job.models import Application

class Userprofile(models.Model):
    user = models.OneToOneField(User, related_name="userprofile", on_delete=models.CASCADE)
    is_employer = models.BooleanField(default=False)
    
User.userprofile = property(lambda u:Userprofile.objects.get_or_create(user=u)[0]) # type: ignore



def __str__(self):
    return self.user


class ConversationMessage(models.Model):
    application = models.ForeignKey(Application, related_name="conversationmessages",on_delete=models.CASCADE)
    content = models.TextField(null=True)


    created_by = models.ForeignKey(User, related_name="conversationmessages",on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']

users/views.py
from django.shortcuts import render,get_object_or_404 ,redirect
from django.contrib.auth.decorators import login_required
from job.models import Application, Job
from xhtml2pdf import pisa
from notification.utilities import create_notification
from django.contrib import messages
from django.contrib.auth.decorators import user_passes_test

# add this decorator to the view that requires authentication

from users.models import ConversationMessage
# Create your views here.
@user_passes_test(lambda user: user.is_authenticated)

def dashboard(request):
   return render ( request,'dashboard.html' ,{'userprofile': request.user.userprofile})

@login_required
def view_application(request, application_id):
   if request.user.userprofile.is_employer:
      application = get_object_or_404(Application  , pk=application_id, job__created_by=request.user) 
   else:
      application = get_object_or_404(Application  , pk=application_id, created_by=request.user) 

   if request.method == "POST":
      content = request.POST.get('content')
      
      if content:
         conversationmessage = ConversationMessage.objects.create(application = application, content=content, created_by=request.user )
         
         # create_notification(request, application.created_by, 'message', extra_id=application.id)
         messages.info(
            request,
            "Message Sent Successfully...")
         return redirect("view_application",application_id=application_id)
   


   return render ( request,'view_application.html' ,{'application': application, 'userprofile': request.user.userprofile})

@login_required
def view_dashboard_job(request, job_id):
   job = get_object_or_404(Job, pk=job_id, created_by=request.user)
   return render (request,'view_dashboard_job.html',{'job': job})

users/templates/dashboard.html
{% include 'header.html' %} 
{% load static %}
{% block content %}
{% if message %}
    <div id="alert" class="alert alert-success">{{ message }}</div>
    <script>
        setTimeout(function() {
            document.getElementById("alert").style.display = "none";
        }, 5000);
    </script>
{% endif %}
  <div class="container">

    <h3 class="title">
      <center style="text-decoration: underline; color: #561c32 ;font-family: 'Courier New', Courier, monospace;">Dashboard</center>
    </h3>

    {% if userprofile.is_employer %}
    {% if messages %}
        <ul class="alert alert-danger">
            {% for message1 in messages %}
                <li>{{ message1 }}</li>
                <script>
                  setTimeout(function () {
                    document.getElementById("alert").style.display = "none";
                  }, 5000);
                </script>
            {% endfor %}
        </ul>
    {% endif %}
<h4 class="subtitle">Welcome  {{userprofile.user}}
  (Employer)
  
</h4>
<div style="display: flex;">

  <div><a href="{% url 'job:add'  %}">
    <input
    type="submit"
    value="Add Job"
    class="m-1 px-5 btn btn-primary"
    style="background-color: #561c32"
    /> 
  </div>
  <!-- <div><a href="{% url 'job:job_pdf'  %}">
    <input
    type="submit"
    value="Job PDF"
    class="m-1 px-5 btn btn-primary"
    style="background-color: #561c32"
    /> <a href=""></a>
  </div> -->
  <a href=""></a>
</div>
<h3 class="subtitle">View all jobs posted</h3>


<table class="table table table-striped table-bordered">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Job Id</th>
      <th scope="col">Job name</th>
      <th scope="col">Date created</th>
      <th scope="col">View Aplicants</th>
      <th scope="col">Edit Job</th>

    </tr>
  </thead>
  <tbody>
    {% for job in request.user.jobs.all %}
    <tr>
      <th scope="row">   {{ job.id }} </a></th>
      <td>  {{ job.title }} ({{job.get_status_display}})</td>
      <td>  {{ job.created_at }}</td>
      <td><a href="{% url 'view_dashboard_job' job.id%}"><i class="fas fa-bars"></i> Candidates</td>
        <td>
          <a href="{% url 'job:edit' job.id %}">
  
            <img src="{% static 'edit.png' %}" width= "20" height="20"alt="My Image">
          </a>
    </tr>
    
    {% empty %}
    <p>You have not posted any jobs yet...</p>
    {% endfor %} 
  </tbody>
</table>
{% else %}
{% if messages %}
<ul class="alert alert-danger">
    {% for message1 in messages %}
        <li>{{ message1 }}</li>
        <script>
          setTimeout(function () {
            document.getElementById("alert").style.display = "none";
          }, 5000);
        </script>
    {% endfor %}
</ul>
{% endif %}
<h4 class="subtitle">Welcome {{userprofile.user}}(Jobseeker) </h4>
<h5 class="subtitle" style="font-family: 'Courier New', Courier, monospace;">All Applications Aplied</h5>
<!-- <style>
  table,
  th,
  td {
    border: 3px solid black;
  }
</style> -->

<table class="table table-striped table-bordered" style="width: 100%">
  <thead class="thead-dark">

    <tr>
      <th scope="col">Job Title</th>
      <th scope="col">First Name</th>
      <th scope="col">Last Name</th>
      <th scope="col">Email</th>
      <th scope="col">Location</th>
      <th scope="col">View Application</th>
      <th scope="col">Delete Application</th>
      <!-- <th scope="col">Edit </th> -->
      <th scope="col">Status </th>
      <th scope="col">View/Send Message</th>



    </tr>
  </thead>
  
  {% for application in request.user.applications.all %}
  <tbody>

    <tr>
      <td>{{ application.job.title }}</td>
      <td>{{ application.first_name }}</td>
      <td>{{ application.last_name }}</td>
      <td>{{ application.email }}</td>
      <td>{{ application.location }}</td>
      <td>
        <a
        href="{% url 'view_application' application.id %}
        "
        >
        <input
        type="submit"
        value="view"
        class="m-1 px-2 btn btn-primary"
          style="background-color: #561c32"
          />
        </a>
      </td>
      <td>
        <form action="{% url 'job:delete_application' application.id %}" method="post">
          {% csrf_token %}
          <input type="submit" value="Delete"   class="m-1 px-2 btn btn-primary"
          style="background-color: #fa0303" onclick="return confirmDelete();">
        </form>
        <!-- <a href="{% url 'job:delete_application' application.id %}">
          <input
          type="submit"
          value="delete"
          class="m-1 px-5 btn btn-primary"
          style="background-color: #fa0303"
          />
        </a> -->
      </td>
      <!-- <td>
        <a href="{% url 'job:edit_app' application.id %}">

          <img src="{% static 'edit.png' %}" width= "20" height="20" alt="My Image">
        </a>
      </td> -->
      <td>     
    {%if application.status == 'pending'%}
    <h6> <span style="color: white; border-radius: 5px; padding: 5px; background-color: black">{{application.status}}</span> </h6>
    {%elif application.status == 'approved'%}
    <h6> <span style="color: green; border-radius: 5px; padding: 5px; background-color: black">{{application.status}}</span> </h6>
    {%elif application.status == 'declined'%}
    <h6> <span style="color: red; border-radius: 5px; padding: 5px; background-color: black">{{application.status}}</span> </h6>
    {%endif%} 
  </td>
<td> 
  <a href="{% url 'view_application' application.id%}">
    <img src="{% static 'mesage.png' %}" width= "30" height="30" alt="My Image">

  </a>
</td>
    </tr>
  </tbody>
    {% empty %}
  <p>You have not applied for any jobs yet..</p>
  {% endfor %}
</table>
{% endif %}





</div>
<script>
  function confirmDelete() {
    return confirm("Are you sure you want to delete?");
  }
</script>
{% endblock %}

users/templates/sidebar.html
{% include 'header.html' %} {% block content %}

<div class="container-fluid">
    <div class="row">
        <div class="col-md-2 sidebar" style="background-color: #333; color: #fff; padding: 20px;">
            <h1>Employer Name</h1>
            <ul class="nav flex-column">
                <li class="nav-item"><a class="nav-link active" href="#">Dashboard</a></li>
                <li class="nav-item"><a class="nav-link" href="#">Profile</a></li>
                <li class="nav-item"><a class="nav-link" href="#">Settings</a></li>
                <li class="nav-item"><a class="nav-link" href="#">Log Out</a></li>
            </ul>
        </div>
        <div class="col-md-10 content" style="padding: 20px;">
            <!-- page content goes here -->
        </div>
    </div>
</div>

{% endblock %}

users/templates/view_application.html
{% include 'header.html' %} {% block content %}

<style>
  p strong {
    min-width: 400px;
  }
</style>
<!-- {% if userprofile.is_employer %}

{% if messages %}
<ul class="alert alert-danger">
    {% for message1 in messages %}
        <li>{{ message1 }}</li>
        <script>
          setTimeout(function () {
            document.getElementById("alert").style.display = "none";
          }, 5000);
        </script>
    {% endfor %}
</ul>
{% endif %}
{% endif %} -->

<div
  class="container"
  style="
    display: flex;
    flex-direction: column;
    justify-content: space-between;
    align-items: center; ;
  "
>
  <!-- start of main container  -->

  <div
    style="margin: 30px; padding: 10px; background-color: #f7f0f5; width: 60%"
    class="card"
  >
    <div style="display: flex; flex-direction:column; justify-content: space-between;    flex-direction: column;
    ">
      <div>
        <h1 class="card-title">Application Details</h1>
        <h2 class="card-subtitle mb-2 text-muted">
          Job Positon: {{ application.job.title }}
        </h2>
        {% if userprofile.is_employer %}

        {%if application.status == 'pending'%}
        <h6>Status: <span style="color: white; border-radius: 5px; padding: 5px; background-color: black">{{application.status}}</span> </h6>
        {%elif application.status == 'approved'%}
        <h6>Status: <span style="color: green; border-radius: 5px; padding: 5px; background-color: black">{{application.status}}</span> </h6>
        <p style="color: green;">Send a message to inform the jobseeker</p>
        {%elif application.status == 'declined'%}
        <h6>Status: <span style="color: red; border-radius: 5px; padding: 5px; background-color: black">{{application.status}}</span> </h6>
        <p style="color: rgb(128, 64, 0);">Send a message to inform the jobseeker</p>

        {%endif%} 
        {%endif%} 

      </div>
      <div>
        <input
          type="submit"
          value="Send a Message"
          class="m-3 px-5 btn btn-primary"
          style="background-color: #561c32; height: 40px; position: static ; padding-left: 0%;"
          id="scroll-down-button"
        />
        {% if userprofile.is_employer %}
       <div style="display: flex; ">

         <form method="POST" action="{% url 'job:approve_job_application' application.id %}">
           {% csrf_token %}
           <div><a href="{% url 'job:approve_job_application' application.id   %}">
            <input
            type="submit"
            value="approved"
            name="status"
            class="m-1 px-5 btn btn-primary"
            style="background-color: green"
            /> 
          </div>
        </form>

          
           
          
          <form method="POST" action="{% url 'job:decline_job_application' application.id %}">
            {% csrf_token %}
            <div><a href="{% url 'job:decline_job_application' application.id %}">
              <input
              type="submit"
              value="declined"
              name="status"

              class="m-1 px-5 btn btn-primary"
              style="background-color: red"
              /> <a href=""></a>
            </div>
          </form>

        </div>
        
        
        

        {% endif %}
      </div>
    </div>

    <hr />
    <small> Date added: {{application.created_at}}</small>

    <div class="card-body">
      <div style="display: flex">
        <h6 style="min-width: 200px; font-weight: bold">First Name:</h6>
        <h6>{{application.first_name}}</h6>
      </div>
      <div style="display: flex">
        <h6 style="min-width: 200px; font-weight: bold">Last Name:</h6>
        <h6>{{application.last_name}}</h6>
      </div>
      <div style="display: flex">
        <h6 style="min-width: 200px; font-weight: bold">Date of birth:</h6>
        <h6>{{application.date_of_birth}}</h6>
      </div>
      <div style="display: flex">
        <h6 style="min-width: 200px; font-weight: bold">Gender:</h6>
        <h6>{{application.gender}}</h6>
      </div>
      <div style="display: flex">
        <h6 style="min-width: 200px; font-weight: bold">Level of Education:</h6>
        <h6>{{application.level_education}}</h6>
      </div>
      <div style="display: flex">
        <h6 style="min-width: 200px; font-weight: bold">Education Acquired:</h6>
        <h6>{{application.education}}</h6>
      </div>
      <div style="display: flex">
        <h6 style="min-width: 200px; font-weight: bold">Email:</h6>
        <h6>{{application.email}}</h6>
      </div>
      <div style="display: flex">
        <h6 style="min-width: 200px; font-weight: bold">Location:</h6>
        <h6>{{application.location}}</h6>
      </div>
      <div style="display: flex">
        <h6 style="min-width: 200px; font-weight: bold">Mobile:</h6>
        <h6>{{application.mobile}}</h6>
      </div>
      <div style="display: flex">
        <h6 style="min-width: 200px; font-weight: bold">Experience:</h6>
        <h6>{{application.experience}}</h6>
      </div>
      <div style="display: flex">
        <h6 style="width: 200px; word-wrap: normal; font-weight: bold">
          Additional Comment:
        </h6>
        <h6>{{application.content}}</h6>
      </div>
      <!-- <div style="display: flex">
        <h6 style="width: 200px; word-wrap: normal; font-weight: bold">
          Resume:
        </h6>
        <h6>{{application.resume}}</h6>
      </div> -->
      <div style="display: flex">
        <h6 style="width: 200px; word-wrap: normal; font-weight: bold">Resume:</h6>
        <div>
          <a href="{{ application.resume.url }}" download>
            <button type="button">Download</button>
          </a>
          <h6>{{ application.resume }}</h6>
        </div>
      </div>
      
      <p></p>
    </div>
  </div>
  <!-- <input
    type="submit"
    value="Message Employer"
    class="m-3  px-5 btn btn-primary"
    style="background-color: #561c32;height :40px; position:static"
    id="scroll-down-button"
  /> -->
</div>
<hr />

<div >
  <h2 class="subtitle">Conversation</h2>
  {% for message in application.conversationmessages.all %}
  <div
    class="notification"
    style="
      display: flex;
      flex-direction: column;
      background-color: #d799b1;
      margin: 20px;
      border-radius: 5px;
      padding: 10px;
    "
  >
    <b
      >{{ message.created_by.username }} - {{ message.created_at|timesince }}
      ago</b
    >
    {{ message.content }}
    <br />
  </div>
  {% empty %}

  <p>No messages yet...</p>
  {% endfor %}
  <form method="post" >
    {% csrf_token %}

    <div class="field">
      <div class="col-sm-12">
        <div class="form-group">
          <textarea
            style="border: 2px solid"
            placeholder="Enter your message"
            type="textarea"
            name="content"
            class="form-control"
            id="id_content"
            rows="5"
          ></textarea>
        </div>
      </div>
    </div>
    <input
      type="submit"
      value="Send"
      class="m-3 px-5 btn btn-primary"
      style="background-color: #561c32"
    />
  </form>
  <script>
    document
      .getElementById("scroll-down-button")
      .addEventListener("click", function () {
        window.scroll({
          top: document.body.scrollHeight,
          behavior: "smooth",
        });
      });
  </script>

  <!-- end of container  -->
  {% endblock %}
</div>

users/templates/view_dashboard_job.html
{% include 'header.html' %}

<!-- <h3 class="title ">
  View all users who applied for the job - {{ job.title }}
</h3> -->
<div
  style="margin: 30px; padding: 10px; background-color: #f7f0f5; width: 60%"
  class="card mx-auto"
>
  <div style="display: flex; justify-content: space-between">
    <div>
      
      <h1 class="card-title">Job Vacancy Details</h1>
      <h2 class="card-subtitle mb-2 text-muted">
        Job Positon: {{ job.title }}
      </h2>
    </div>
    <input
      type="submit"
      value="View All Candidates"
      class="m-3 px-5 btn btn-primary"
      style="background-color: #561c32; height: 40px; position: static"
      id="scroll-down-button"
    />
  </div>

  <hr />
  <small> Date added: {{job.created_at}}</small>

  <div class="card-body">
    <div style="display: flex">
      <h6 style="min-width: 200px; font-weight: bold">Job Title:</h6>
      <h6>{{job.title}} ({{job.get_status_display}}) </h6>
    </div>
    <div style="display: flex">
      <h6 style="min-width: 200px; font-weight: bold">About Job:</h6>
      <h6>{{job.about_job}}</h6>
    </div>
    <div style="display: flex">
      <h6 style="min-width: 200px; font-weight: bold">Skillset Required</h6>
      <h6>{{job.skillset_required}}</h6>
    </div>
    <div style="display: flex">
      <h6 style="min-width: 200px; font-weight: bold">Experience:</h6>
      <h6>{{job.experience}}</h6>
    </div>
    <div style="display: flex">
      <h6 style="min-width: 200px; font-weight: bold">Salary Range</h6>
      <h6>{{job.salary}}</h6>
    </div>
    <div style="display: flex">
      <h6 style="min-width: 200px; font-weight: bold">Department Name:</h6>
      <h6>{{job.department_name}}</h6>
    </div>
    <div style="display: flex">
      <h6 style="min-width: 200px; font-weight: bold">Deadline to Submit:</h6>
      <h6>{{job.deadline}}</h6>
    </div>
    
    
    <p></p>
  </div>
</div>

<form method="get" action="{% url 'job:search_jobs'%}">
  <div class="form-group column">
      {% if job.id %}
      <input type="hidden"  name="job_id" value="{{ job.id }}">
    {% endif %}
      

    <br>
    
    <div style="display: flex;">

      <label for="status" class="col-sm-0 col-form-label" style="margin-left: 50px; ;">Filter:</label>
      <div class="col-sm-5">
        <select class="form-control" id="status" name="status">
          <option value="">All</option>
          <option value="approved" {% if status == 'approved' %}selected{% endif %}>Approved</option>
          <option value="pending" {% if status == 'pending' %}selected{% endif %}>Pending</option>
          <option value="declined" {% if status == 'declined' %}selected{% endif %}>Declined</option>
        </select>
      </div>
      <div class="form-group column">
        <div class="col-sm-12">
          <button type="submit" class="btn " style="background-color:#561c32;color:white">Search</button>
        </div>
      </div>
    </div>
  </div>
 
</form>

<div class="container">
  <table class="table">
    <thead class="thead-dark table-striped table-bordered">
      <tr>
        <th scope="col">Job id</th>
        <th scope="col">Aplicant Name</th>
        <th scope="col">Email</th>
        <th scope="col">Location</th>
        <th scope="col">Time Applied</th>

        <th scope="col">View Application</th>
        <th scope="col">Status</th>

      </tr>
    </thead>
    <tbody>
      {% for application in job.applications.all %}

      <tr>
        <th>{{ job.id }}</th>
        <td>{{application.first_name}} {{application.last_name}}</td>
        <td>{{application.email}}</td>
        <td>{{application.location}}</td>
        <td>{{application.created_at}}</td>

        <td>
          <a href="{% url 'view_application' application.id %}"
            ><i class="fas fa-list"></i>Application</a
          >
        </td>
          <td>     
            {%if application.status == 'pending'%}
            <h6> <span style="color: white; border-radius: 5px; padding: 5px; background-color: black">{{application.status}}</span> </h6>
            {%elif application.status == 'approved'%}
            <h6> <span style="color: green; border-radius: 5px; padding: 5px; background-color: black">{{application.status}}</span> </h6>
            {%elif application.status == 'declined'%}
            <h6> <span style="color: red; border-radius: 5px; padding: 5px; background-color: black">{{application.status}}</span> </h6>
            {%endif%} 
          </td>
        
      </tr>

      {% empty %}
      <p>No user applied for this job</p>
      {% endfor %}
    </tbody>
  </table>
</div>

<script>

  document.getElementById("scroll-down-button").addEventListener("click", function() {
    window.scroll({
      top: document.body.scrollHeight,
      behavior: "smooth"
    });
  });
</script>