EmployeeRecordMgmt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from . import views  # Import views from main app

# from django.contrib.auth.models import Group

admin.site.site_header = "Jobseeker Records"
# admin.site.unregister(Group)



urlpatterns = [
    path('admin/', admin.site.urls),
    path('employee/',include("employee.urls")),
    path('job/',include("job.urls")),
    path('users/',include("users.urls")),
    path('notification/',include("notification.urls")),
    path('', views.home, name='home'),  # Add this line for the hero page



    # path('images/covers')                        

] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

job/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings
from .api import api_search


app_name = "job"

urlpatterns = [
    path("api/search",api_search,name = "api_search"),
    path("search/",views.search,name = "search"),
    path("<int:job_id>/edit", views.edit, name="edit"),
    path("<int:application_id>/edit_app", views.edit_app, name="edit_app"),
    path("search_jobs", views.search_jobs, name="search_jobs"),

    path("<int:job_id>", views.job_detail, name="job_detail"),
    path("job/add" ,views.add, name="add"),
    path("<int:job_id>/apply_for_job/" ,views.apply_for_job, name="apply_for_job "),
    path("delete_application/<int:application_id>",views.delete_application,name="delete_application"),
    path("job_pdf",views.job_pdf,name="job_pdf"),
    path('job-application/<int:application_id>/approve/', views.approve_job_application, name='approve_job_application'),
    path('job-application/<int:application_id>/decline/', views.decline_job_application, name='decline_job_application'),

    ]



urlpatterns += static (settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

job/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Count


GENDER = (('M', 'Male'), ('F', 'Female'), ('O', 'Other'))



class Job(models.Model):

    

    COMPUTER_SUPPORT_SPECIALIST = 'Computer Support Specialist'
    HARDWARE_ENGINEER = 'Hardware Engineer'
    COMPUTER_SYSTEM_ANALYST = 'Computer System Analyst'
    SOFTWARE_DEVELOPER = 'Software Developer'
    PROGRAMMER = 'Programmer'
    WEB_DEVELOPER = 'Web Developer'
    NETWORK_ENGINEER = 'Network Engineer'
    SOFTWARE_TESTER = 'Software Tester'
    FRONTEND_DEVELOPER = "Frontend Developer"
    BACKEND_DEVELOPER = "Backend Developer"

    CHOICES_SIZE =   ( (COMPUTER_SUPPORT_SPECIALIST ,'COMPUTER_SUPPORT_SPECIALIST'),
    ( HARDWARE_ENGINEER ,'HARDWARE_ENGINEER'),
    ( COMPUTER_SYSTEM_ANALYST, 'COMPUTER_SYSTEM_ANALYST' ),
    ( SOFTWARE_DEVELOPER, 'SOFTWARE_DEVELOPER'),
    ( PROGRAMMER , 'PROGRAMMER'),
    ( WEB_DEVELOPER,'WEB_DEVELOPER'),
    ( NETWORK_ENGINEER,'NETWORK_ENGINEER'),
    ( SOFTWARE_TESTER,'SOFTWARE_TESTER'),
    (FRONTEND_DEVELOPER,"FRONTEND_DEVELOPER"),
    (BACKEND_DEVELOPER,"BACKEND_DEVELOPER")
    )

      
    ACTIVE = 'active'
    EMPLOYED = 'employed'
    ARCHIVED = 'archived'

    
    CHOICES_STATUS = (
        (EMPLOYED,'Employed'),
        (ACTIVE,'Active' ),
        (ARCHIVED,'Archived' )
     )

    title = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    skillset_required = models.TextField(null=True)
    about_job= models.TextField(blank=True, null=True)
    image = models.ImageField(upload_to="covers/",null=True,blank=True)
    experience = models.CharField(max_length=100,null=True)
    salary = models.CharField(max_length=50,null=True)
    deadline = models.CharField(max_length=50,null=True)

    department_name = models.CharField( max_length=30,choices=CHOICES_SIZE)

    
    created_by = models.ForeignKey(User,
                                   related_name="jobs",
                                   on_delete=models.CASCADE)
    status = models.CharField(max_length=20,choices=CHOICES_STATUS,default='active')
    
    def __str__(self):
        return self.title
    
        
    class Meta:
        ordering = ['-created_at']

    
class Application(models.Model):

    APPROVED = 'approved'
    PENDING = 'pending'
    DECLINED = 'declined'

    CHOICES_STATUS = (
        (APPROVED,'Approved'),
        (PENDING,'Pending' ),
        (DECLINED,'Declined' )
    )
    
    HIGH_SCHOOL = 'High School'
    ASSOCIATE_DEGREE = 'Associate Degree'
    BACHELOR_DEGREE = 'Bachelor Degree'
    MASTER_DEGREE = 'Master Degree'
    DOCTORATE = 'Doctorate'
    PROFESSIONAL_DEGREE = 'Professional Degree'
    CERTIFICATE = 'Certificate'
    DIPLOMA = 'Diploma'
    


    EDUCATION_CHOICES = ((HIGH_SCHOOL, 'High School'),
        (ASSOCIATE_DEGREE, 'Associate Degree'),
        (BACHELOR_DEGREE, "Bachelor's Degree"),
        (MASTER_DEGREE, "Master's Degree"),
        (DOCTORATE, 'Doctoral Degree'),
        (PROFESSIONAL_DEGREE, 'Professional Degree'),
        (CERTIFICATE, 'Certificate'),
        (DIPLOMA, 'Diploma')
    )

    job = models.ForeignKey(Job,
                            related_name='applications',
                             on_delete=models.CASCADE)
    first_name = models.CharField(max_length=200, null=True, blank=True)
    last_name = models.CharField(max_length=200, null=True, blank=True)
    date_of_birth = models.CharField(max_length=20, blank=True, null=True)
    gender = models.CharField(max_length=1,
                              choices=GENDER,
                              blank=False,
                              null=True)
    email = models.EmailField(max_length=70, blank=True, unique=True)
    location = models.CharField(
        max_length=104,
        null=True
    )
    mobile = models.IntegerField(null=True, blank=True)
    education   = models.CharField( max_length=2553, null=True, blank=True)

    level_education = models.CharField(max_length=30, choices=EDUCATION_CHOICES)


    content = models.TextField()
    experience = models.TextField()
    
    resume  = models.FileField( upload_to="resumes/", null=True, blank=True)
    
    created_at = models.DateTimeField(auto_now_add=True,null=False)
    status = models.CharField(max_length=20,choices=CHOICES_STATUS,default='pending')

    created_by = models.ForeignKey(User,
                                   related_name="applications",
                                   on_delete=models.CASCADE)

    class Meta:
        ordering = ['-created_at']


    

class ApplicationSummary(Application):
        class Meta:
          proxy = True
        verbose_name = 'Application Summary'

        def job_title(self):
            return self.job.title

job/forms.py
from django import forms
from .models import Job, Application

class AddJobForm(forms.ModelForm):
    class Meta:
        model = Job
        fields = ['title','skillset_required','about_job','experience','salary','deadline', 'department_name','image']

class ApplicationForm(forms.ModelForm):
    class Meta:
        model = Application
        fields = ['first_name','last_name','date_of_birth','gender','education','email','location','content','experience','mobile', 'resume', 'level_education']

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if Application.objects.filter(email=email).exists():
            raise forms.ValidationError('This email has already been used to apply for a job.')
        return email

job/views.py
from django.contrib import messages

from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponse

from django.contrib.auth.decorators import login_required
from .models import Job, Application
from .forms import AddJobForm, ApplicationForm
from notification.utilities import create_notification

from django.http import FileResponse
import io
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle

# Create your views here.
def approve_application(request, application_id):
    application = get_object_or_404(Application, pk=application_id)
    if request.method == 'POST':
            status = request.POST.get('status')
            if status == 'approved':
                application.status = 'approved'
                application.save()
                # return a response indicating that the application has been approved
            elif status == 'declined':
                application.status = 'declined'
                application.save()
                # return a response indicating that the application has been declined
        # return a response indicating that the form was not submitted correctly
            print(status)
        # return a response indicating that the user is not authorized to approve this application

def job_pdf(request):
    buf = io.BytesIO()
    #create canvas
    c = canvas.Canvas(buf, pagesize=letter, bottomup=0)
    #create text object
    textob = c.beginText()
    textob.setTextOrigin(inch, inch)
    textob.setFont("Helvetica", 14)

    # lines = [
    #     "This is line 1",
    #     "This is line 2",
    #     "This is line 3",

    # ]
    jobs = Job.objects.all()
    lines = []

    for job in jobs:
        lines.append("All jobs added by Employer") # type: ignore
        lines.append("======================")
        lines.append(job.title.encode('utf-8')) # type: ignore
        lines.append(str(job.created_at)) # type: ignore
        lines.append(job.skillset_required.encode('utf-8')) # type: ignore
        lines.append(job.about_job.encode('utf-8'))# type: ignore
        lines.append(job.experience.encode('utf-8'))# type: ignore
        lines.append(job.salary.encode('utf-8'))# type: ignore
        lines.append(job.deadline.encode('utf-8'))# type: ignore
        lines.append(job.department_name.encode('utf-8')) # type: ignore
        lines.append("======================") # type: ignore

    for line in lines:
        textob.textLine(line)

    c.drawText(textob)
    c.showPage()
    c.save() 
    buf.seek(0)


    return FileResponse(buf, as_attachment=True, filename="job.pdf")

def search(request):
    return render(request, "search.html")

def delete_application(request, application_id):
    application = Application.objects.get(pk=application_id)
    application.delete()
    return redirect("dashboard")


def job_detail(request, job_id):
    job = Job.objects.get(pk=job_id)
   

    return render(request, 'job_detail.html', {'job': job, 'userprofile':request.user.userprofile})
from django.shortcuts import render, redirect
from .models import Application

def approve_job_application(request, application_id):
    application = Application.objects.get(id=application_id)
    application.status = Application.APPROVED
    application.save()
    messages.info(
            request,
            "Application Accepted...")
    return redirect('view_application', application_id=application_id)

def decline_job_application(request, application_id):
    application = Application.objects.get(id=application_id)
    application.status = Application.DECLINED
    application.save()
    messages.info(
            request,
            "Application declined...")
    return redirect('view_application', application_id=application_id)

def search_jobs(request):
  status = request.GET.get('status', '')
  job_id = request.GET.get('job_id', '')



  if job_id:
        job = Job.objects.get(id=job_id)
        if status:
            applications = job.applications.filter(status=status) # type: ignore
        else:
            applications = job.applications.all() # type: ignore
  else:
        if status:
            applications = Application.objects.filter(status=status)
        else:
            applications = Application.objects.all()
#   if status:
#     applications = Application.objects.filter(status=status)
#   else:
#     applications = Application.objects.all()
#     messages.info(
#             request,
#             "Found Results...")
  context = {
    'applications': applications,
    'status': status
  }

  return render(request, 'search_job.html', context)

@login_required
def apply_for_job(request, job_id):
    job = Job.objects.get(pk=job_id)
   
    if request.method == 'POST':
        form = ApplicationForm(request.POST)
    
      

        if form.is_valid():
            email = form.cleaned_data['email']
            mobile = form.cleaned_data['mobile']
       
            if Application.objects.filter(job=job, email=email).exists():
                messages.info(request, 'This email has already been used to apply for this job')
            if Application.objects.filter(job=job, mobile=mobile).exists():
                messages.info(request, 'This mobile number has already been used to apply for this job')
                return render(request, 'apply_for_job.html', {'form': form, 'error_message': 'This mobile number has already been used.'})



            else:
                application = form.save(commit=False)
                application.job = job
                application.created_by = request.user
                application.resume = request.FILES["resume"]
                application.save()
                messages.success(request, 'Applied successfully.')
                create_notification(request, job.created_by, 'application', extra_id=application.id)
                return redirect("dashboard")
        # if form.is_valid():
        #     application = form.save(commit=False)
        #     application.job = job
        #     application.created_by = request.user
        #     application.resume = request.FILES["resume"]
            
            
        #     application.save()
        #     messages.info(
        #     request,
        #     "Applied successfully...")
        #     create_notification(request,
        #                         job.created_by,
        #                         'application',
        #                         extra_id=application.id)

        #     return redirect("dashboard")
 
    else:
        form = ApplicationForm()
    context = {
       
        'form': form,
        'job': job
    }
    return render(request, 'apply_for_job.html', context)

    

@login_required
def add(request):

    if request.method == 'POST':
        form = AddJobForm(request.POST)

        if form.is_valid():
            job = form.save(commit=False)
            job.created_by = request.user
            
            job.save()
            messages.info(
            request,
            "Job Added successfully...")

            return redirect("dashboard")

            # return HttpResponse('added a job succesfully')
            # return http ('login')

    else:
        form = AddJobForm()

    return render(request, 'add_job.html', {'form': form})


@login_required
def edit(request,job_id):
    job = get_object_or_404(Job,pk=job_id,created_by=request.user)
    if request.method == 'POST':
        form = AddJobForm(request.POST,instance=job)

        if form.is_valid():
            job = form.save(commit=False)
            job.status = request.POST.get('status')
            
            job.save()
            messages.info(
            request,
            "Job Edited successfully...")
            return redirect("dashboard")

            

    else:
        form = AddJobForm(instance=job)

    return render(request, 'edit_job.html', {'form': form,'job':job})


@login_required
def edit_app(request,application_id):
    application = get_object_or_404(Application,pk=application_id,created_by=request.user)
    if request.method == 'POST':
        form = ApplicationForm(request.POST,instance=application)

        if form.is_valid():
            application = form.save(commit=False)
            
            application.save()
            messages.info(
            request,
            "Application Edited successfully...")
            return redirect("dashboard")
        

            
    else:
        form = ApplicationForm(instance=application)

    return render(request, 'edit_application.html', {'form': form,'application':application})

job/templates/edit_application.html
{% include 'header.html' %} {% block content %}
<center
  class="title"
  style="
    font-size: 20px;
    font-weight: 100;
    text-decoration: underline;
    color: #561c32;
  "
>
  Edit Application
</center>
<div>
  <form
    method="POST"
    style="
      color: #561c32;
      font: 100% / normal sans-serif;
      justify-content: space-between;
      font-size: large;
      padding: 20px;
      justify-content: start;
      align-items: flex-start;
    "
    enctype="multipart/form-data"
  >
    {% csrf_token %} {%if form.errors %} {% for error in form.errors %}
    <div class="alert alert-danger">
      Error in {{ error }} Field or field is empty
    </div>
    {% endfor %} {% endif %}

    <div
      class="card mx-auto"
      style="width: 70%; background-color: #d5abb9; justify-content: center"
    >
      <div class="col-sm-12">
        <div class="form-group">
          <label> Firstname:-</label>
          <input
            style="border: 2px solid"
            type="text"
            placeholder="Your First Name"
            name="first_name"
            pattern="[A-Za-z]+"
            title="Only letters accepted"
            class="form-control"
            id="id_first_name"
            value=" {% if application.first_name %}{{ application.first_name }}{% endif %}"
            v-model="first_name"
            required
          />
        </div>
      </div>
      <div class="col-sm-12">
        <div class="form-group">
          <label> Lastname:-</label>
          <input
            style="border: 2px solid"
            type="text"
            name="last_name"
            pattern="[A-Za-z]+"
            title="Only letters accepted"
            placeholder="Your Last Name"
            class="form-control"
            id="id_last_name"
            value=" {% if application.last_name %}{{ application.last_name }}{% endif %}"
            v-model="last_name"
            required
          />
        </div>
      </div>
      <div class="col-sm-12">
        <div class="form-group">
          <label>Date of Birth:-</label>
          <input
            style="border: 2px solid"
            type="date"
            name="date_of_birth"
            placeholder="Your Date of Birth"
            title="Valid date of birth"
            min="1960-01-01"
            max="2005-12-31"
            class="form-control"
            id="id_date_of_birth"
            value="{{ application.date_of_birth }}"
            required
          />
        </div>
      </div>
      <div class="col-4">
        <div class="form-group">
          <label>Gender</label>
          <div style="margin-left: 20px">
            <label>Male</label>
            <input type="radio" placeholder="gender" name="gender" value="M"
            {% if application.gender == "M" %} checked {% endif %} id="id_gender"
            />
          </div>
          <div style="margin-left: 20px">
            <label>Female</label>
            <input type="radio" placeholder="gender" name="gender" value="F" 
            {% if application.gender == "F" %} checked {% endif %} id="id_gender"
            />
          </div>
          <div style="margin-left: 20px">
            <label>Other</label>
            <input type="radio" placeholder="gender" name="gender" value="O" 
            {% if application.gender == "O" %} checked {% endif %} id="id_gender"
            />
          </div>
        </div>
      </div>
      <div class="col-sm-12">

      <div class="form-group">
        <label >Level of Education:</label>
        <select  name="level_education"   >
          <option value="">-- Select --</option>
          <option value="High School" {% if application.level_education == "High School" %}selected{% endif %} >High School

          </option>
          <option value="Associate Degree"{% if application.level_education == "Associate Degree" %}selected{% endif %}>Associate Degree

          </option>
          <option value="Bachelor Degree"{% if application.level_education == "Bachelor Degree" %}selected{% endif %}>Bachelor's Degree

          </option>
          <option value="Master Degree" {% if application.level_education == "Master Degree" %}selected{% endif %}>Master's Degree</option>
          <option value="Doctoral Degree"{% if application.level_education == "Doctoral Degree" %}selected{% endif %}>Doctoral Degree</option>
          <option value="Professional Degree"{% if application.level_education == "Professional Degree" %}selected{% endif %}>Professional Degree</option>
          <option value="Certificate"{% if application.level_education == "Certificate" %}selected{% endif %}>Certificate</option>
          <option value="Diploma"{% if application.level_education == "Diploma" %}selected{% endif %}>Diploma</option>
          
        </select>
      </div>
  </div>
      <div class="col-sm-12">
        <div class="form-group">
          <label>Education acquired:-</label>
          <textarea
            style="border: 2px solid"
            placeholder="Levels of Education Acquired"
            type="textarea"
            name="education"
            class="form-control"
            id="education"
            rows="5"
            required
          >
{% if application.education %}{{ application.education }}{% endif %}</textarea
          >
        </div>
      </div>
      <div class="col-sm-12">
        <div class="form-group">
          <label> Email:-</label>
          <input
            style="border: 2px solid"
            type="email"
            name="email"
            placeholder="Your Email"
            class="form-control"
            id="id_email"
            value=" {% if application.email %}{{ application.email }}{% endif %}"
            required
          />
        </div>
      </div>
      <div class="col-sm-12">
        <div class="form-group">
          <label> Your Location(County):-</label>
          <input
            style="border: 2px solid"
            type="text"
            placeholder="Your location"
            name="location"
            class="form-control"
            pattern="[A-Za-z]+"
            title="Only letters accepted"
            id="id_location"
            value=" {% if application.location %}{{ application.location }}{% endif %}"
            required
          />
        </div>
      </div>
      <div class="col-sm-12">
        <div class="form-group">
          <label> Your Mobile Number:-</label>
          <input
            style="border: 2px solid"
            name="mobile"
            type="tel"
          pattern="\+254[0-9]{3}[0-9]{3}[0-9]{3}"
          minlength="13"
          maxlength="13"
          title="Only numbers accepted"
            class="form-control"
            id="id_mobile"
            value=" {% if application.mobile %}{{ application.mobile }}{% endif %}"
            required value="+254"
          />
        </div>
      </div>
      <div class="col-sm-12">
        <div class="form-group">
          <label>Any Work Experience Acquired:-</label>
          <textarea
            style="border: 2px solid"
            type="textarea"
            name="experience"
            placeholder="Any Experience Acquired"
            class="form-control"
            id="id_experience"
            rows="5"
            required
          >
 {% if application.experience %}{{ application.experience }}{% endif %}           
    </textarea
          >
        </div>
      </div>
      <div class="col-sm-12">
        <div class="form-group">
          <label>Any Other Information/Comment:-</label>
          <textarea
            style="border: 2px solid"
            type="textarea"
            name="content"
            placeholder="Any Comment"
            class="form-control"
            id="id_content"
            rows="5"
            required
          >
{% if application.content %}{{ application.content }}{% endif %} </textarea
          >
        </div>
      </div>
      <div>
        <label for="file">Resume:-</label>
        <br />
        <input
          type="file"
          id="id_resume"
          name="resume"
          accept=".pdf,.doc,.docx"
          {{%
          if
          not
          application.resume
          %}required{%
          endif
          %}
          required
        />
      </div>
      <div>
        <input
          type="submit"
          value="Save Changes"
          class="m-2 px-3 btn btn-primary"
          style="background-color: #561c32; justify-content: center"
        />
      </div>
    </div>
  </form>
</div>
{% endblock %}
<!-- <script>
    const EditjobApplication = {
      data() {
        return {
          first_name: "{{ application.first_name }}",
          last_name: "{{ application.skillset_required }}",
          date_of_birth: "{{ application.experience }}",
          email: "{{ application.email }}",
      
          errors: [],
        };
      },
      delimiters: ["[[", "]]"],
      methods: {
        validateForm(e) {
          this.errors = [];

          if (this.first_name === "") {
            this.errors.push("The First Name field is missing!");
          }

          if (this.last_name === "") {
            this.errors.push("The Last name field is missing!");
          }

          if (this.date_of_birth === "") {
            this.errors.push("The Date of Birth field is missing!");
          }


          if (this.email === "") {
            this.errors.push("The Email field is missing!");
          }

        
          
          if (this.errors.length) {
            e.preventDefault();
            return false;
          } else {
            return true;
          }
        },
      },
    };
    Vue.createApp(EditjobApplication).mount("#edit-job-application");
  </script> -->

job/templates/job_detail.html
{% include 'header.html' %} {% block content %}
<div style="display: flex" class="container">
  <div style="margin: 30px 20px 5px 20px">
    <h1 style="font-size: x-large">
      <strong>{{ job.title }} ({{ job.get_status_display }})</strong>
    </h1>
    <br />
    <h6><i class="fas fa-briefcase"></i> {{ job.experience }}</h6>
    <h6><i class="fas fa-dollar-sign"></i>{{ job.salary }}</h6>

    {% if not userprofile.is_employer and job.status == 'active' %}

    <a
      class="btn custom-btn"
      style="
        font-weight: 100;
        font-size: 1em;
        border: solid 2px grey;
        color: #f7edee;
        background-color: #561c32;
      "
      href="{% url 'job:apply_for_job ' job.id %}"
      >Apply now<i class="fas fa-hand-point-up"></i
    ></a>
    {% elif not userprofile.is_employer and not job.status == 'active' %}
    <p style="color: red; border: 2px solid red; border-radius: 5px; padding: 5px">This job is not available!</p>
    {% elif userprofile.is_employer %}
    <p style="color: red; border: 2px solid red; border-radius: 5px; padding: 5px">Only job seekers can apply!</p>
    {% endif %}
    <h6><i class="fas fa-timer"></i>Last Date to Apply {{ job.deadline }}</h6>
  </div>

  <div style="margin: 30px; width: 100%">
    <h1 style="font-size: x-large; font-style: italic">
      <strong>Skillset Required</strong>
    </h1>

    <p class="is-size-4">{{job.skillset_required }}</p>
    <h1 style="font-size: x-large; font-style: italic">
      <strong>About Job</strong>
    </h1>

    <p>{{job.about_job}}</p>

    <h1 style="font-size: x-large; font-style: italic">
      <strong>Department Name</strong>
    </h1>
    <p>{{job.department_name}}</p>
  </div>
</div>
{% endblock %} {% include 'footer.html' %}

job/templates/search_job.html
{% include 'header.html' %} 
{% load static %}

{% block content %}
{% if message %}
    <div id="alert" class="alert alert-success">{{ message }}</div>
    <script>
        setTimeout(function() {
            document.getElementById("alert").style.display = "none";
        }, 5000);
    </script>
{% endif %}
{% if applications %}
    <center style="text-decoration: underline; color: #561c32 ;font-family: 'Courier New', Courier, monospace;"> Search Results:

    </center>


<div class="container">
    <table class="table "width="100%">
      <thead class="thead-dark table-striped table-bordered">
        <tr>
          <th scope="col">Job id</th>
          <th scope="col">Aplicant Name</th>
          <th scope="col">Email</th>
          <th scope="col">Location</th>
          <th scope="col">Time Applied</th>
  
          <th scope="col">View Application</th>
          <th scope="col">Status</th>
  
        </tr>
      </thead>
      <tbody>
        {% for application in applications %}
        <tr>
          <th>{{ application.job.id }}</th>
          <td>{{application.first_name}} {{application.last_name}}</td>
          <td>{{application.email}}</td>
          <td>{{application.location}}</td>
          <td>{{application.created_at}}</td>
  
          <td>
            <a href="{% url 'view_application' application.id %}"
              ><i class="fas fa-list"></i>Application</a
            >
          </td>
            <td>     
                {% if application.status == 'pending' %}
                <h6><span style="color: white; border-radius: 5px; padding: 5px; background-color: black">{{ application.status }}</span></h6>
              {% elif application.status == 'approved' %}
                <h6><span style="color: green; border-radius: 5px; padding: 5px; background-color: black">{{ application.status }}</span></h6>
              {% elif application.status == 'declined' %}
                <h6><span style="color: red; border-radius: 5px; padding: 5px; background-color: black">{{ application.status }}</span></h6>
              {% endif %} 
            </td>
          
        </tr>
        
        {% endfor %}
      </tbody>
   
    </table>
    {% else %}
    <div
    class="card mx-auto"
    style="width: 50%; background-color: #d5abb9; justify-content: center; margin-top: 5%;"
  >
    <div class="col-sm-12">
      <div class="form-group">
        <h3 style="text-align: center;">No applications found.</h3>
        {% endif %}
        <a href="{% url 'dashboard' %}" style="justify-content: center;text-align:center; display:flex;"  class="btn btn-secondary">Go Back</a>
        {% endblock %}
      
        </div>
        </div>
    </div>
 
  