EmployeeRecordMgmt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from . import views  # Import views from main app

# from django.contrib.auth.models import Group

admin.site.site_header = "Jobseeker Records"
# admin.site.unregister(Group)



urlpatterns = [
    path('admin/', admin.site.urls),
    path('employee/',include("employee.urls")),
    path('job/',include("job.urls")),
    path('users/',include("users.urls")),
    path('notification/',include("notification.urls")),
    path('', views.home, name='home'),  # Add this line for the hero page



    # path('images/covers')                        

] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

employee/urls.py
from django.urls import path
from employee import views

app_name = "employee"

urlpatterns = [
    path("base", views.base, name="base"),
    path("about",views.about,name="about"),
    path("contact",views.contact,name="contact"),
    path("help",views.help,name="help"),

    path("register", views.register, name="register"),
    path("logout",views.logoutuser,name="logout"),
    path("login", views.Login, name="login"),
    # patterns(r'^images/(?P<path>.*)$', 'django.views.static.serve',
    #              {'document_root': settings.MEDIA_ROOT}),
              
    ]

job/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings
from .api import api_search


app_name = "job"

urlpatterns = [
    path("api/search",api_search,name = "api_search"),
    path("search/",views.search,name = "search"),
    path("<int:job_id>/edit", views.edit, name="edit"),
    path("<int:application_id>/edit_app", views.edit_app, name="edit_app"),
    path("search_jobs", views.search_jobs, name="search_jobs"),

    path("<int:job_id>", views.job_detail, name="job_detail"),
    path("job/add" ,views.add, name="add"),
    path("<int:job_id>/apply_for_job/" ,views.apply_for_job, name="apply_for_job "),
    path("delete_application/<int:application_id>",views.delete_application,name="delete_application"),
    path("job_pdf",views.job_pdf,name="job_pdf"),
    path('job-application/<int:application_id>/approve/', views.approve_job_application, name='approve_job_application'),
    path('job-application/<int:application_id>/decline/', views.decline_job_application, name='decline_job_application'),

    ]



urlpatterns += static (settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

employee/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Contact(models.Model):
    full_name = models.CharField(max_length=200, null=True, blank=True)

    email = models.EmailField(blank=True, unique=True, null=True)
    content = models.TextField(null=True,blank=True)

employee/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages

from users.models import Userprofile
from job.models import Job
from employee.models import Contact


# Create your views here.
# @login_required
def base(request):
    jobs = Job.objects.all()[0:8]
    return render(request, "base.html", {'jobs': jobs})


def about(request):
    return render(request, 'about.html')


def contact(request):
    if request.method == "POST":
        cfull_name = request.POST.get("full_name")
        cemail = request.POST.get("email")
        ccontent = request.POST.get("content")
 
        # Handle invalid email address
        query = Contact(full_name=cfull_name, email=cemail, content=ccontent)
        query.save()
        messages.info(
            request,
            "Thanks for contacting us we will get back to you soon...")
        return redirect("employee:contact")
    return render(request, 'contact.html')


def help(request):
    return render(request, 'help.html')


def register(request):
    if request.method == "POST":
        fname = request.POST.get('firstname')
        email = request.POST.get('email')
        password = request.POST.get('password')
        name = request.POST.get("username")
         # Check if the username or email already exists in the database


        if User.objects.filter(username=name).exists():
            messages.error(request, 'Username already exists!!!')
            return redirect('employee:register')

        if User.objects.filter(email=email).exists():
            messages.error(request, 'Email already exists!!!')
            return redirect('employee:register')
        
        user = User.objects.create_user(name, email, password)
        if fname:
           user.first_name = fname

        user.save()
        account_type = request.POST.get('account_type', 'jobseeker')
        if account_type == 'employer':
            userprofile = Userprofile.objects.create(user=user,
                                                     is_employer=True)
            userprofile.save()

            return redirect("dashboard")  
        else:
            userprofile = Userprofile.objects.create(user=user)
            userprofile.save()

        messages.info(request, "Sign-up successful")
        login(request, user)

        return redirect("employee:login")
    else:

        return render(request, "register.html", locals())


def Login(request):
    if request.method == "POST":
        name = request.POST.get('username')
        # email = request.POST.get('email')
        password = request.POST.get('password')

        user1 = authenticate(
            request,
            username=name,
            password=password)

        if user1 is not None:
            login(request, user1)
          
            message = "Login successful\U0001F44D"
            # return redirect("dashboard")  

            return render(request, "base.html", {'message': message})

        else:
           
            try:
                user1 = User.objects.get(username=name)
                messages.error(request, 'Invalid password!!!')
            except User.DoesNotExist:
                messages.error(request, 'Invalid username or password!!!')
            return redirect("employee:login")

    return render(
        request,
        "login.html",
    )


def logoutuser(request):
    logout(request)
    return redirect("employee:base")

employee/templates/about.html
{% include 'header.html' %}

{% block content %}
<div style="background-color: #dbb7c3;margin-top:0%; margin-top: 0; ">

  <div style="display: flex; margin: 20px; " >
    <div style="justify-items: end; padding: 10px;">
      <h1 style="color: #561c32">About us <i class="fas fa-people-group"></i></h1>
      <p > We at <strong>4IQ  Technologies</strong> are a technology company (or tech company) that focuses primarily on the manufacturing, support, research and development of — most commonly computing, telecommunication and consumer electronics-based — technology-intensive products and services
       which include businesses relating to digital electronics, software, optics, new energy and internet-related services such as cloud storage and e-commerce services.
       We ensure that our customers are fully satisfied by the services and goods we provide to them making them trust us fully
       and recommend us to others who need our services.Welcome
       
       Broadly speaking, We majorly engage in the research, development, and manufacture of technologically based goods and services. We create, design, and manufacture computers, mobile and home appliances softwares and provide products and services related to information technology.
      </p>
      
      
    </div>
    <div>
      <img style="border-radius: 20px;  mix-blend-mode: color-burn;  " src="https://t4.ftcdn.net/jpg/03/08/69/75/360_F_308697506_9dsBYHXm9FwuW0qcEqimAEXUvzTwfzwe.jpg" alt="">
    </div>
  </div>
  
</div>
{% endblock  %}
{% include 'footer.html' %}

employee/templates/contact.html
{% include 'header.html' %}
<script src="path/to/validator.min.js">

</script>
<script>
    const form = document.querySelector('form');
    const emailInput = form.querySelector('#email');
    
    form.addEventListener('submit', function(event) {
      event.preventDefault()
      
      // Get the value of the email input field
      const email = emailInput.value;
      
      // Validate the email using Validator.js
      if (validator.isEmail(email)) {
        // If the email is valid, submit the form
        form.submit();
      } else {
        // If the email is invalid, show an error message
        alert('Please enter a valid email address.');
      }
    });
</script>
{% if messages %}
    <ul class="alert alert-danger">
        {% for message1 in messages %}
            <li>{{ message1 }}</li>
        {% endfor %}
    </ul>
{% endif %}
{%if form.errors %} {% for error in form.errors %}
  <div class="alert alert-danger"> Error at {{ error }} Field</div>
  {% endfor %} {% endif %} 

{% if form.errors %}
{% for field, errors in form.errors.items %}
  {% for error in errors %}
    <div class="alert alert-danger"> Error at {{ field }} field: {{ error }}</div>
  {% endfor %}
{% endfor %}
{% endif %}
<center>
  <div class="container" style="font-family: arial narrow; color: #561c32">
    <strong>
      <h2 style="margin-top: 20px">We'd love to hear from you</h2>
    </strong>

    <br />
    <h4>
      Whether you have a question about the jobs,how to apply or anything
      else,our team is ready to hear from you
    </h4>
  </div>
</center>
<div class="card shadow m-5">
  <div class="card-body" style="background-color: #f7f0f5">
    <h5 class="p-2" style="border-bottom: 2px solid orange; color: #561c32">
      Get In Touch With Us
    </h5>
    <div class="container-fluid">
      <form method="POST"  name="contact">
        {% csrf_token %}

        {% if form.errors %}
        {% for field, errors in form.errors.items %}
          {% for error in errors %}
            <div class="alert alert-danger"> Error at {{ field }} field: {{ error }}</div>
          {% endfor %}
        {% endfor %}
        {% endif %}
        <div class="form-row">
          <div class="col-sm-6">
            <div class="form-group">
              <label> First Name</label>
              <input
                type="text"
                name="full_name"
                id="id_fullname"
                pattern="[A-Za-z]+"
                title="Only letters accepted"
                class="form-control"
                placeholder="Enter your First Name"
                required
              />
            </div>
          </div>
          <br />

          <div class="col-sm-6">
            <div class="form-group">
              <label> Email</label>
              <input
                type="email"
                name="email"
                title="Enter a valid Email"
                id="id_email"
                pattern="[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}$"
                placeholder="johndoe@gmail.com"
                class="form-control"
                required
              />
            </div>
          </div>
          <br />

          <div class="col-sm-12">
            <div class="form-group">
              <label>Your Message</label>
              <textarea
                style="border: 2px line"
                placeholder="Enter Your Message..."
                type="textarea"
                name="content"
                class="form-control"
                id="id_content"
                rows="5"
                required
              ></textarea>
            </div>
          </div>
        </div>
        <input
          type="submit"
          value="Contact Us"
          class="m-2 px-3 btn btn-primary"
          style="background-color: #561c32"
        />
      </form>
    </div>
  </div>
</div>

{% include 'footer.html' %}

employee/templates/footer.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Employee Recruitement management system</title>

    <link
    rel="stylesheet"
    href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
    crossorigin="anonymous"
     />
    <link
    rel="stylesheet"
    href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
    crossorigin="anonymous"
    />
  
</head>
<body>
    <!-- Remove the container if you want to extend the Footer to full width. -->

    <!-- Footer -->
    <footer
            class="text-center text-lg-start text-white"
            style="background-color: #561c32"
            >
      <!-- Section: Social media -->
      <section
               class="d-flex justify-content-between p-4"
               style="background-color: #f0deef"
               >
        <!-- Left -->
        <div class="me-5">
          <span style="color: #561c32;">Get connected with us on social networks:</span>
        </div>
        <!-- Left -->
  
        <!-- Right -->
        <div>
          <a href="" class="text-black me-4">
            <i class="fab fa-facebook-f"></i>
          </a>
          <a href="" class="text me-4">
            <i class="fab fa-twitter"></i>
          </a>
          <a href="" class="text me-4">
            <i class="fab fa-google"></i>
          </a>
          <a href="" class="text me-4">
            <i class="fab fa-instagram"></i>
          </a>
        
        </div>
        <!-- Right -->
      </section>
      <!-- Section: Social media -->
  
      <!-- Section: Links  -->
      <section >
        <div class=" text-center text-md-start mt-5">
          <!-- Grid row -->
          <div class="row mt-3">
            <!-- Grid column -->
            <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
              <!-- Content -->
              <h6 class="text-uppercase fw-bold">4IQ Technologies</h6>
              <hr
                  class="mb-4 mt-0 d-inline-block mx-auto"
                  style="width: 60px; background-color: #ffffff; height: 2px"
                  />
                  <p>We are located in Nairobi,Tom Mboya Street near Archives</p>
              
            </div>
            <!-- Grid column -->
  
            <!-- Grid column -->
            
            <!-- Grid column -->
  
            <!-- Grid column -->
            <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
              <!-- Links -->
              <h6 class="text-uppercase fw-bold">Useful links</h6>
              <hr
                  class="mb-4 mt-0 d-inline-block mx-auto"
                  style="width: 60px; background-color: #ffffff; height: 2px"
                  />
              <p>
                <a href="{% url 'employee:about'%}" class="text-white">About Us</a>
              </p>
              <p>
                <a href="{% url 'employee:contact'%}" class="text-white">Contact Us</a>
              </p>
              <p>
                <a href="{% url 'employee:base'%}" class="text-white">Home Page</a>
              </p>
              <p>
                <a href="{% url 'employee:help' %}" class="text-white">Help</a>
              </p>
            </div>
            <!-- Grid column -->
  
            <!-- Grid column -->
            <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
              <!-- Links -->
              <h6 class="text-uppercase fw-bold">Contact</h6>
              <hr
                  class="mb-4 mt-0 d-inline-block mx-auto"
                  style="width: 60px; background-color: #ffffff; height: 2px"
                  />
              <p><i class="fas fa-home mr-3"></i> Nairobi, NBO 10012, Kenya</p>
             <p> <i class="fas fa-envelope mr-3"></i> 
                <link> 4iqtechnologies254@gmail.com </link>
              </p>
              <p><i class="fas fa-phone mr-3"></i> + 254 742466933</p>
              <p><i class="fas fa-print mr-3"></i> + 254 742466933</p>
            </div>
            <!-- Grid column -->
          </div>
          <!-- Grid row -->
        </div>
      </section>
      <!-- Section: Links  -->
  
      <!-- Copyright -->
      <div
           class="text-center p-3"
           style="background-color: rgba(0, 0, 0, 0.2)"
           >
        © 2023 Copyright:
        <a class="text-white" href=""
           >4iqtechnologies.com</a
          >
      </div>
      <!-- Copyright -->
    </footer>
    <!-- Footer -->
  
  </div>
  <!-- End of .container -->
  <script
  src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
  integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
  crossorigin="anonymous"
></script>
<script
  src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
  integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
  crossorigin="anonymous"
></script>
<script
  src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
  integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
  crossorigin="anonymous"
></script>
</body>
</html>

employee/templates/header.html
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>4IQ TECHNOLOGIES Employee Recruitement management system</title>
    {% load static %}

    <link rel="stylesheet" href="{% static 'css/mystyle.css' %}" />

    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />

    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    />
    <link
      rel="stylesheet"
      href="https://use.fontawesome.com/releases/v5.6.3/css/all.css"
      integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/"
      crossorigin="anonymous"
    />
  </head>
  <body>
    <nav
      class="navbar navbar-expand-lg"
      style="display: flex; background-color: #561c32"
    >
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbar"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div
        class="collapse navbar-collapse"
        id="navbar"
        style="padding: 5px 30px"
      >
        <div class="navbar-nav" style="width: 100%">
          <a
            class="navbar-brand"
            style="color: #d5abb9"
            href="{% url 'employee:base' %}"
            >4IQ Technologies</a
          >

          <a
            style="color: white"
            class="nav-item nav-link"
            id="home"
            href="{% url 'employee:base' %}"
          >
            <i class="fa fa-home"></i>Home</a
          >

          <a
            style="color: white"
            class="nav-item nav-link"
            href="{% url 'employee:about'%}"
            ><i class="fas fa-address-card"></i>About Us</a
          >

          <a
            style="color: white"
            class="nav-item nav-link"
            href="{% url 'employee:contact'%}"
            ><i class="fas fa-phone"></i>Contact Us</a
          >
          <a
            style="color: white"
            class="nav-item nav-link"
            href="{% url 'employee:help'%}"
            ><i class="fas fa-phone"></i>Help</a
          >
          {% if request.user.is_authenticated %}
          <a
            style="color: white"
            class="nav-item nav-link"
            href="{% url 'employee:logout' %}"
            ><i class="fas fa-sign-in-alt"></i>Logout</a
          >
          {% else %}
          <a
            style="color: white"
            class="nav-item nav-link"
            href="{% url 'employee:register' %}"
            ><i class="fas fa-sign-in-alt"></i>Sign-Up</a
          >
          <a
            style="color: white"
            class="nav-item nav-link"
            href="{% url 'employee:login' %}"
            ><i class="fas fa-sign-in-alt"></i>login</a
          >

          {% endif %} {% if request.user.is_authenticated %}

          <a
            style="color: white"
            class="nav-item nav-link"
            href="{% url 'dashboard' %}"
            ><i class="fas fa-sign-in-alt fa-beat"></i>Dashboard</a
          >
          <a
            style="color: white"
            class="nav-item nav-link"
            href="{% url 'job:search' %}"
          >
            <img
              style="font-size: 20px"
              src="{% static 'newsearch.png' %}"
              width="20"
              height="20"
              alt="My Image"
            />
            Search</a
          >
          {% if request.user.notification1.count > 0 %}
          <a
            style="color: white"
            class="nav-item nav-link"
            href="{% url 'notifications' %}"
            ><i class="fas fa-envelope"></i>Notifications
            ({{request.user.notification1.count}})</a
          >
          {% endif %} {% endif %}

        </div>
      </div>
    </nav>
    <!--End of nav-->

    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.js"></script>
    <script src="https://unpkg.com/vue@next"></script>
    <!-- <script async defer src="https://cdnjs.cloudflare.com/ajax/libs/vue/2.7.14/vue.common.prod.min.js" integrity="sha512-vwjHx54j9x6k6Mz7g7fR1d8f9CoCqKGv3eTaYShGsa0+SmmXgl6cq/DF+fek2/akIYUw6ZlnHU5UFEkpo+xF1Q==" crossorigin="anonymous" referrerpolicy="no-referrer"></script> -->
    {% block scripts %} {% endblock %}
  </body>
</html>

employee/templates/help.html
{% include 'header.html' %}
{% block content %}

<div style="margin-top: auto;">
	  

	<div class="container my-4" style="background-color:#dbb7c3 ; ;">
		<h1 class="text-center" style="color: #561c32" >4IQ Technologies Employee Recruitment System Help</h1>
		<hr>
		<h3>Getting Started</h3>
		<p>If you are a new user, please register for an account by clicking on the "Sign-Up" button on the login page. Once you have registered, you can log in to the system using your username and password.</p>
        <p> You can choose an account type either a "Jobseeker" and "Employer"</p>

		<h3>Creating a Job Posting</h3>
		<p>To create a new job posting, click on the "Add Job" button on the dashboard. You will be prompted to enter the job title, description, and other details. Once you have filled in all the required fields, click on the "Save" button to create the job posting.</p>
        <p style="color: #b73d28;">Only if you choose a "Employer" as the account type</p>
		<h3>Viewing Applications for Employers</h3>
		<p>You can view all the applications for a particular job posting by clicking on the "View Applications"  button (in the view job table) next to the job posting on the dashboard. You can then view each application individually and take action on it. </p>
        <h3>Applying for a job for Jobseekers</h3>
        <p>Job Seekers are able to apply for jobs by seraching for a specific job they want,view job details,apply for the job and view applications on their dashboard</p>
		<h3>Edit Job Applications</h3>
		<p>If a job vacancy is no longer available the Employer can edit the job vacancy and declare it 
			<span>archived</span>
			

		</p>

	</div>

</div>
{% endblock  %}
<br>
{% include 'footer.html' %}

employee/templates/login.html
{%include 'header.html'%}
<script>
  function togglePasswordVisibility() {
    var passwordField = document.getElementById("password");
    if (passwordField.type === "password" ) {
      passwordField.type = "text";
    } else {
      passwordField.type = "password";
    }
  }
</script>
{% if messages %}
{% for message in messages %}
  <div class="alert alert-danger">{{ message }}</div>
  <script>
    setTimeout(function () {
      document.getElementById("alert").style.display = "none";
    }, 5000);
  </script>
{% endfor %}
{% endif %}


<div class="card m-5" style="margin: auto; border: none">
  <div class="card-body shadow " style="background-color: #f7f0f5; margin: auto">
    <h5 class="p-2" style="border-bottom: 2px solid orange; color: #561c32">
      Login to your account
    </h5>
    <div class="container-fluid">
      <form method="post" name="signup" onsubmit="return checkpassword()">
        {% csrf_token %}
        <div class="form-row" style="display: flex; flex-direction: column;">
          <div >
            <div class="form-group">
              <label> Username</label>
              <input
                type="text"
                name="username"
                class="form-control"
                placeholder="Enter Your Username"
                required
              />
            </div>
          </div>
          <!-- <div class="col-sm-12">
                        <div class="form-group">
                         <label> Email</label>
                         <input type="email" name="email" class="form-control" placeholder="Enter Your Email" required>
                        </div>

                    </div> -->
          <div >
            <div class="form-group">
              <label> Password</label>
              <input
                type="password"
                id="password"
                name="password"
                class="form-control"
                placeholder="Enter Your Password"
                required
              />
              <button type="button" onclick="togglePasswordVisibility()">&#x1F441;</button>

            </div>
          </div>
        </div>
        <!-- <br /> -->
        <input
          type="submit"
          value="Login"
          class="px-3 btn btn-primary"
          style="background-color: #561c32; width: 100%"
        />
        <p>
          Do not have an account?<a href="{% url 'employee:register' %}"
            >Sign-Up</a
          >
        </p>
      </form>
     
    </div>
  </div>
</div>